from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def __init__(self):
        super().__init__()
        print("Ui Mainwindow initialization")

    def setupUi(self, MainWindow):

        print("Class Name for setupUi: " + self.__class__.__name__)

        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(696, 443)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")



        self.preview_label = QtWidgets.QLabel(self.centralwidget)
        self.preview_label.setGeometry(QtCore.QRect(380, 50, 60, 16))
        self.preview_label.setObjectName("preview_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 350, 291, 38))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.date_label = QtWidgets.QLabel(self.layoutWidget)
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_4.addWidget(self.date_label)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setKeyboardTracking(False)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setCalendarPopup(True)



        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.proceedButton = QtWidgets.QPushButton(self.layoutWidget)
        self.proceedButton.setObjectName("proceedButton")
        self.horizontalLayout_4.addWidget(self.proceedButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(370, 10, 321, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.template_label = QtWidgets.QLabel(self.layoutWidget1)
        self.template_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.template_label.setObjectName("template_label")
        self.horizontalLayout_5.addWidget(self.template_label)
        self.templateComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.templateComboBox.setMinimumSize(QtCore.QSize(250, 30))
        self.templateComboBox.setMaximumSize(QtCore.QSize(250, 30))
        self.templateComboBox.setObjectName("templateComboBox")
        self.horizontalLayout_5.addWidget(self.templateComboBox)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 51, 333, 281))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.songVerticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.songVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.songVerticalLayout.setObjectName("songVerticalLayout")
        self.song_1H = QtWidgets.QHBoxLayout()
        self.song_1H.setObjectName("song_1H")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_1H.addItem(spacerItem2)
        self.song_1_label = QtWidgets.QLabel(self.layoutWidget2)
        self.song_1_label.setObjectName("song_1_label")
        self.song_1H.addWidget(self.song_1_label)
        self.song_1_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.song_1_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.song_1_comboBox.setBaseSize(QtCore.QSize(0, 0))
        self.song_1_comboBox.setObjectName("song_1_comboBox")
        self.song_1H.addWidget(self.song_1_comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_1H.addItem(spacerItem3)
        self.songVerticalLayout.addLayout(self.song_1H)
        self.song_2H = QtWidgets.QHBoxLayout()
        self.song_2H.setObjectName("song_2H")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_2H.addItem(spacerItem4)
        self.song_2_label = QtWidgets.QLabel(self.layoutWidget2)
        self.song_2_label.setObjectName("song_2_label")
        self.song_2H.addWidget(self.song_2_label)
        self.song_2_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.song_2_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.song_2_comboBox.setObjectName("song_2_comboBox")
        self.song_2H.addWidget(self.song_2_comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_2H.addItem(spacerItem5)
        self.songVerticalLayout.addLayout(self.song_2H)
        self.song_3H = QtWidgets.QHBoxLayout()
        self.song_3H.setObjectName("song_3H")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_3H.addItem(spacerItem6)
        self.song_3_label = QtWidgets.QLabel(self.layoutWidget2)
        self.song_3_label.setObjectName("song_3_label")
        self.song_3H.addWidget(self.song_3_label)
        self.song_3_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.song_3_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.song_3_comboBox.setObjectName("song_3_comboBox")
        self.song_3H.addWidget(self.song_3_comboBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_3H.addItem(spacerItem7)
        self.songVerticalLayout.addLayout(self.song_3H)
        self.song_4H = QtWidgets.QHBoxLayout()
        self.song_4H.setObjectName("song_4H")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_4H.addItem(spacerItem8)
        self.song_4_label = QtWidgets.QLabel(self.layoutWidget2)
        self.song_4_label.setObjectName("song_4_label")
        self.song_4H.addWidget(self.song_4_label)
        self.song_4_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.song_4_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.song_4_comboBox.setObjectName("song_4_comboBox")
        self.song_4H.addWidget(self.song_4_comboBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_4H.addItem(spacerItem9)
        self.songVerticalLayout.addLayout(self.song_4H)
        self.song_5H = QtWidgets.QHBoxLayout()
        self.song_5H.setObjectName("song_5H")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_5H.addItem(spacerItem10)
        self.song_5_label = QtWidgets.QLabel(self.layoutWidget2)
        self.song_5_label.setObjectName("song_5_label")
        self.song_5H.addWidget(self.song_5_label)
        self.song_5_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.song_5_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.song_5_comboBox.setObjectName("song_5_comboBox")
        self.song_5H.addWidget(self.song_5_comboBox)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_5H.addItem(spacerItem11)
        self.songVerticalLayout.addLayout(self.song_5H)
        self.song_6H = QtWidgets.QHBoxLayout()
        self.song_6H.setObjectName("song_6H")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_6H.addItem(spacerItem12)
        self.song_6_label = QtWidgets.QLabel(self.layoutWidget2)
        self.song_6_label.setObjectName("song_6_label")
        self.song_6H.addWidget(self.song_6_label)
        self.song_6_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.song_6_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.song_6_comboBox.setObjectName("song_6_comboBox")
        self.song_6H.addWidget(self.song_6_comboBox)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_6H.addItem(spacerItem13)
        self.songVerticalLayout.addLayout(self.song_6H)
        self.song_7H = QtWidgets.QHBoxLayout()
        self.song_7H.setObjectName("song_7H")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_7H.addItem(spacerItem14)
        self.song_7_label = QtWidgets.QLabel(self.layoutWidget2)
        self.song_7_label.setObjectName("song_7_label")
        self.song_7H.addWidget(self.song_7_label)
        self.song_7_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.song_7_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.song_7_comboBox.setObjectName("song_7_comboBox")
        self.song_7H.addWidget(self.song_7_comboBox)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_7H.addItem(spacerItem15)
        self.songVerticalLayout.addLayout(self.song_7H)
        self.song_8H = QtWidgets.QHBoxLayout()
        self.song_8H.setObjectName("song_8H")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_8H.addItem(spacerItem16)
        self.song_8_label = QtWidgets.QLabel(self.layoutWidget2)
        self.song_8_label.setObjectName("song_8_label")
        self.song_8H.addWidget(self.song_8_label)
        self.song_8_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.song_8_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.song_8_comboBox.setObjectName("song_8_comboBox")
        self.song_8H.addWidget(self.song_8_comboBox)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.song_8H.addItem(spacerItem17)
        self.songVerticalLayout.addLayout(self.song_8H)
        self.preview_image = QtWidgets.QLabel(self.centralwidget)
        self.preview_image.setGeometry(QtCore.QRect(450, 60, 231, 201))
        self.preview_image.setMouseTracking(False)
        self.preview_image.setAutoFillBackground(False)
        self.preview_image.setLineWidth(1)
        self.preview_image.setText("")
        self.preview_image.setObjectName("preview_image")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(21, 10, 189, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.songCount = QtWidgets.QLabel(self.layoutWidget3)
        self.songCount.setObjectName("songCount")
        self.horizontalLayout.addWidget(self.songCount)
        self.songCountComboBox = QtWidgets.QComboBox(self.layoutWidget3)
        self.songCountComboBox.setObjectName("songCountComboBox")
        self.horizontalLayout.addWidget(self.songCountComboBox)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.preview_label.raise_()
        self.preview_image.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 22))
        self.menubar.setObjectName("menubar")
        self.menuPPT = QtWidgets.QMenu(self.menubar)
        self.menuPPT.setObjectName("menuPPT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuPPT.addSeparator()
        self.menubar.addAction(self.menuPPT.menuAction())
        self.date_label.setBuddy(self.dateEdit)
        self.template_label.setBuddy(self.templateComboBox)
        self.song_1_label.setBuddy(self.song_1_comboBox)
        self.song_2_label.setBuddy(self.song_2_comboBox)
        self.song_3_label.setBuddy(self.song_3_comboBox)
        self.song_4_label.setBuddy(self.song_4_comboBox)
        self.song_5_label.setBuddy(self.song_5_comboBox)
        self.song_6_label.setBuddy(self.song_6_comboBox)
        self.song_7_label.setBuddy(self.song_7_comboBox)
        self.song_8_label.setBuddy(self.song_8_comboBox)
        self.songCount.setBuddy(self.songCountComboBox)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.preview_label.setText(_translate("MainWindow", "Preview"))
        self.date_label.setText(_translate("MainWindow", "Date:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy"))
        self.proceedButton.setText(_translate("MainWindow", "Proceed"))
        self.template_label.setText(_translate("MainWindow", "Template: "))
        self.song_1_label.setText(_translate("MainWindow", "Song #1:"))
        self.song_2_label.setText(_translate("MainWindow", "Song #2:"))
        self.song_3_label.setText(_translate("MainWindow", "Song #3:"))
        self.song_4_label.setText(_translate("MainWindow", "Song #4:"))
        self.song_5_label.setText(_translate("MainWindow", "Song #5:"))
        self.song_6_label.setText(_translate("MainWindow", "Song #6:"))
        self.song_7_label.setText(_translate("MainWindow", "Song #7:"))
        self.song_8_label.setText(_translate("MainWindow", "Song #8:"))
        self.songCount.setText(_translate("MainWindow", " Song Count:"))
        self.menuPPT.setTitle(_translate("MainWindow", "PPT"))

